config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users,
             module: 'users',
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords'
             },
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

  namespace :api, defaults: { format: :json } do
    namespace :v3 do
      devise_for :users,
                 controllers: {
                   sessions: 'api/v3/users/sessions',
                   registrations: 'api/v3/users/registrations'
                 },
                 path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
                 }
      resources :bookmarks
      resources :drafts
      resources :pseuds
      resources :tags do
        collection { get 'autocomplete' }
      end
      resources :works
    end
  end

  resources :tags do
    resources :works
  end
  resources :users do
    resources :pseuds do
      resources :works
    end
  end
  resources :works

  root to: 'home#index'
end

app/models/works/chapter.rb
# frozen_string_literal: true

class Chapter < ApplicationRecord
  include Creatable
  include Positionable
  include Sanitized

  sanitize_fields title:    [:html_entities],
                  notes:    [:html, :css],
                  endnotes: [:html, :css],
                  summary:  [:html],
                  content:  [:html, :css, :multimedia]

  ### ASSOCIATIONS
  belongs_to :work

  ### VALIDATIONS
  validates :content,
            presence: true,
            length: {
              minimum: ArchiveConfig.chapters[:content_min]
            }
  validates :endnotes,
            length: {
              maximum: ArchiveConfig.works[:notes_max]
            }
  validates :notes,
            length: {
              maximum: ArchiveConfig.works[:notes_max]
            }
  validates :summary,
            length: {
              maximum: ArchiveConfig.works[:summary_max]
            }
  validates :title,
            length: {
              maximum: ArchiveConfig.works[:title_max]
            }

  ### CALLBACKS
  before_validation :clean_title, :count_words
  after_commit :queue_callbacks

  ### CLASS METHODS
  def self.posted
    where(posted: true)
  end

  def self.update_positions(work_id)
    return unless work_id
    reposition!(where(work_id: work_id))
  end

  ### INSTANCE METHODS
  def clean_title
    self.title = title.strip if title
  end

  def count_words
    self.word_count = Otw::WordCounter.new(content).count
  end

  # Put callbacks that affect other models here
  def queue_callbacks
    ChapterPostingJob.perform_later(self)
  end
end

app/models/works/creatorship.rb
# frozen_string_literal: true

class Creatorship < ApplicationRecord
  ### ASSOCIATIONS
  belongs_to :pseud
  belongs_to :creation, polymorphic: true

  ### VALIDATIONS

  ### CALLBACKS

  ### CLASS METHODS

  ## INSTANCE METHODS
end

app/models/works/draft.rb
# frozen_string_literal: true

# Draft work class for unposted work management
class Draft < ApplicationRecord
  include Sanitized

  belongs_to :user

  WORK_ATTRIBUTES = %w(
    type
    title
    summary
    notes
    endnotes
    expected_number_of_chapters
    backdate
    restricted
    anon_commenting_disabled
    moderated_commenting_enabled
    language_id
  ).freeze

  TAG_FIELDS = %w(
    ratings
    archive_warnings
    categories
    fandoms
    characters
    relationships
    freeforms
  ).freeze

  FIELDS = WORK_ATTRIBUTES + TAG_FIELDS + %w(
    chapters
    series
    collections
    cocreators
    recipients
    parents
  )

  # Define getter and setter methods for each field that
  # read from and write to the metadata hash
  FIELDS.each do |field|
    define_method field do
      if instance_variable_get("@#{field}").nil?
        instance_variable_set("@#{field}", metadata[field])
      end
      instance_variable_get("@#{field}")
    end

    define_method "#{field}=" do |value|
      instance_variable_set("@#{field}", value)
      self.metadata ||= {}
      self.metadata[field] = value
    end
  end

  # You can't set a database-level default for this field
  # so initialize it here to avoid nils
  # Also, stringify passed in keys to avoid conflicts
  after_initialize do |draft|
    draft.metadata = (draft.metadata || {}).stringify_keys
  end

  before_validation :sanitize_metadata

  ### VALIDATIONS ###

  # Just prevent anything really nutty here
  validates :metadata,
            length: {
              maximum: ArchiveConfig.chapters[:content_max] + 10_000
            }

  ### CLASS METHODS ###
  
  def self.for_user(user)
    order(:updated_at)
    # where(user_id: user.id).order('updated_at DESC')
  end

  ### INSTANCE METHODS ###

  def update_from_params(data)
    self.user_id ||= data.delete(:user_id)
    update_metadata(data)
    save
  end

  def update_metadata(new_data)
    metadata_will_change!
    new_data.each_pair do |key, value|
      send("#{key}=", value) if FIELDS.include?(key.to_s)
    end
    self
  end

  def series_data
    metadata['series'] || {}
  end

  def series_title
    series_data['title']
  end

  def series_position
    series_data['position']
  end

  def work_data
    metadata.slice(*WORK_ATTRIBUTES)
  end

  def chapter_data
    metadata['chapters']
  end

  def tag_data
    TAG_FIELDS.each_with_object({}) do |field, tags|
      tags[field.classify] = metadata[field]
    end
  end

  def creators
    user ? [user.default_pseud_id].compact : []
  end

  def as_json(_options = {})
    json_data = attributes.slice("id", "user_id", "created_at", "updated_at")
    json_data.merge(metadata)
  end

  ### SANITIZE DATA ###

  # This is more complicated than usual because the data is serialized
  def sanitize_metadata
    return unless metadata_changed?
    sanitizers = {
      'title'    => [:html_entities],
      'notes'    => [:html, :css],
      'endnotes' => [:html, :css],
      'summary'  =>  [:html]
    }
    sanitizers.each do |field, sanitizers|
      value = metadata[field]
      next if value.blank?
      self.metadata[field] = sanitized_value(value, sanitizers)
    end
    sanitize_associations
  end

  # Run our embedded associations through the sanitizer
  def sanitize_associations
    sanitize_association('chapters', Chapter.fields_to_sanitize)
    sanitize_association('series', Series.fields_to_sanitize)
  end

  # For each embedded association, sanitize its fields
  def sanitize_association(assoc, sanitizer_info)
    current_data = self.metadata[assoc]
    return unless current_data.is_a?(Array)
    self.metadata[assoc] = current_data.map do |item|
      sanitize_item(item, sanitizer_info)
    end
  end

  def sanitize_item(item, sanitizer_info)
    clean_item = item.dup
    sanitizer_info.each_pair do |field, sanitizers|
      field = field.to_s
      value = clean_item[field]
      clean_item[field] = sanitized_value(value, sanitizers)
    end
    clean_item
  end
end

app/models/works/serial_work.rb
# frozen_string_literal: true

class SerialWork < ApplicationRecord
  belongs_to :series
  belongs_to :work
end

app/models/works/series.rb
# frozen_string_literal: true

class Series < ApplicationRecord
  include Bookmarkable
  include Creatable
  include Sanitized

  sanitize_fields title:        [:html_entities],
                  series_notes: [:html, :css],
                  summary:      [:html]

  has_many :serial_works
  has_many :works, through: :serial_works

  ### VALIDATIONS ###

  validates :series_notes, length: {
    allow_blank: true,
    maximum: ArchiveConfig.series[:notes_max]
  }

  validates :summary, length: {
    allow_blank: true,
    maximum: ArchiveConfig.series[:summary_max]
  }

  validates :title,
            presence: true,
            length: { maximum: ArchiveConfig.series[:title_max] }
end

app/models/works/stat_counter.rb
# frozen_string_literal: true

# Cache class for work statistics
class StatCounter < ApplicationRecord
  belongs_to :work
end

app/models/works/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  include Bookmarkable
  include Collectible
  include Creatable
  include Sanitized
  include Taggable

  sanitize_fields title:    [:html_entities],
                  notes:    [:html, :css],
                  endnotes: [:html, :css],
                  summary:  [:html]

  searchkick mappings: WorkSearch.mappings,
             settings: WorkSearch.settings

  ### ASSOCIATIONS ###

  belongs_to :language

  has_many :chapters

  has_many :serial_works
  has_many :series, through: :serial_works

  has_one :stat_counter

  ### VALIDATIONS ###

  validates :endnotes,
            length: { maximum: ArchiveConfig.works[:notes_max] }
  validates :notes,
            length: { maximum: ArchiveConfig.works[:notes_max] }
  validates :summary,
            length: { maximum: ArchiveConfig.works[:summary_max] }
  validates :title,
            presence: true,
            length: {
              minimum: ArchiveConfig.works[:title_min],
              maximum: ArchiveConfig.works[:title_max]
            }

  ### CALLBACKS ###

  before_validation :clean_title

  ### CLASS METHODS ###

  def self.posted
    where(posted: true)
  end

  def self.unhidden
    where(hidden_by_admin: false)
  end

  def self.unrestricted
    where(restricted: false)
  end

  ### INSTANCE METHODS ###

  # creates a language_short method
  delegate :short, to: :language, prefix: true, allow_nil: true

  def clean_title
    self.title = (title || '').strip
  end

  def search_data
    WorkSearch.document(self)
  end

  def set_completeness
    posted_chapter_count = chapters.select { |c| c.posted? }.length
    self.complete = (posted_chapter_count == chapters_expected)
  end

  def set_word_count
    posted_word_counts = chapters.map { |c| c.posted? ? c.word_count : 0 }
    self.word_count = posted_word_counts.sum
  end

  alias_attribute :anonymous?, :in_anon_collection
  alias_attribute :unrevealed?, :in_unrevealed_collection
  alias_attribute :chapters_expected, :expected_number_of_chapters
end

app/models/works/work_blurb.rb
class WorkBlurb
  include ActionView::Helpers::TagHelper
  delegate :url_helpers, to: 'Rails.application.routes'

  attr_accessor :output_buffer
  attr_reader :work

  def initialize(work_document)
    @work = work_document
  end

  def as_json(options = {})
    doc = work.dup
    if unrevealed?
      return {
        id: id,
        title: "Mystery Work"
      }
    end
    if anonymous?
      doc.delete(:creators)
      doc.delete(:authors_to_sort_on)
    end
    doc
  end

  def id
    work['id']
  end

  def title
    work['title']
  end

  def summary
    work['summary']
  end

  def language
    work['language'] || 'en'
  end

  def revised_at
    work['revised_at']&.to_date
  end

  def date_string
    revised_at&.strftime("%d %b %Y")
  end

  def anonymous?
    work['anonymous']
  end

  def unrevealed?
    work['unrevealed']
  end

  def word_count
    work['word_count']
  end

  def chapter_count
    current = work['chapters_posted']
    expected = work['chapters_expected'] || '?'
    "#{current}/#{expected}"
  end

  def comments_count
    work['comments_count']
  end

  def bookmarks_count
    work['bookmarks_count']
  end

  def kudos_count
    work['kudos_count']
  end

  def hit_count
    work['hit_count']
  end

  def collection_count
    collections.length
  end

  def collections
    work['collections'] || []
  end

  def series
    work['series'] || []
  end

  def tags
    work['tags'] || []
  end

  def creators
    work['creators'] || []
  end

  def icon_block
    blocks = [
      rating_icon_li,
      media_icon_li,
      warning_icon_li,
      complete_icon_li
    ]
    "<ul class='required-tags'>#{blocks.join}</ul>".html_safe
  end

  def rating_icon_li
    rating = tags.find { |tag| tag['type'] == 'Rating' }
    val= rating['name']
    name = val.split(" ").first.downcase
    content_tag(:li, class: 'rating') do
      content_tag(:span, class: "rating-#{name}", title: val) do
        content_tag(:span, class: "text") { val }
      end
    end
  end

  def media_icon_li
    media = 'text'
    content_tag(:li, class: 'media') do
      content_tag(:span, class: "media-#{media}", title: media) do
        content_tag(:span, class: "text") { media }
      end
    end
  end

  def warning_icon_li
    warnings = tags.select { |tag| tag['type'] == 'ArchiveWarning' }
    names = warnings.map { |w| w['name'] }
    desc  = if names.length == 1 && names.first =~ /No Archive Warnings/
              "no"
            elsif names.length == 1 && names.first =~ /Choose Not/
              "maybe"
            else
              "yes"
            end
    val = names.join(', ')
    content_tag(:li, class: 'warning') do
      content_tag(:span, class: "warning-#{desc}", title: val) do
        content_tag(:span, class: "text") { val }
      end
    end
  end

  def complete_icon_li
    val = complete? ? 'Complete' : 'Incomplete'
    content_tag(:li, class: 'wip') do
      content_tag(:span, class: "#{val.downcase}", title: val) do
        content_tag(:span, class: "text") { val }
      end
    end
  end

  def complete?
    work['complete']
  end

  def creator_links
    return [{ name: 'Anonymous' }] if work['anonymous']
    creators.map{ |creator| creator_link(creator) }
  end

  def creator_link(creator)
    url = url_helpers.user_pseud_works_url(
      user_id: creator['user_login'],
      pseud_id: creator['name'],
      id: creator['name'],
      host: ArchiveConfig.host
    )
    { name: byline(creator), url: url }
  end

  def byline(creator)
    name = creator['name']
    login = creator['user_login']
    name == login ? name : "#{name} (#{login})"
  end

  def creator_link_string
    return 'Anonymous' if work['anonymous']
    creator_links.map do |link|
      "<a href='#{link[:url]}'>#{link[:name]}</a>"
    end.join(', ').html_safe
  end

  def series_links
    series.map do |ser|
      { url: "/series/#{ser['id']}", name: ser['title'] }
    end
  end

  def series_html_links
    series.map do |ser|
      count = ser['position']
      url = "/series/#{ser['id']}"
      title = ser['title']
      "Part #{count} of <a href='#{url}'>#{title}</a>"
    end
  end

  def collection_count_link
    "<a href='/works/#{id}/collections'>#{collection_count}</a>".html_safe
  end

  def tag_links(tag_type)
    return [] unless tags.present?
    tags.map { |tag| tag_link(tag) if tag['type'] == tag_type }.compact
  end

  def tag_link(tag)
    param = tag['name'].parameterize[0..50]
    url = url_helpers.tag_works_url(
      tag_id: "#{tag['id']}-#{param}",
      host: ArchiveConfig.host
    )
    { name: tag['name'], url: url }
  end

  def fandom_links
    tag_links('Fandom')
  end

  def fandom_link_string
    fandom_links.map do |fandom_link|
      "<a href='#{fandom_link[:url]}'>#{fandom_link[:name]}</a>"
    end.join(', ').html_safe
  end

  def tag_li_list
    tag_types = %w(ArchiveWarning Relationship Character Category Freeform)
    tag_types.map do |tag_type|
      tag_links(tag_type).map do |link|
        content_tag(:li, class: tag_type.underscore.pluralize) do
          content_tag(:a, href: link[:url], class: 'tag') do
            link[:name]
          end
        end
      end
    end.flatten.join.html_safe
  end
end

app/controllers/api/v3/works_controller.rb
# frozen_string_literal: true

class Api::V3::WorksController < Api::V3::BaseController
  before_action :authenticate_user!, only: [:create]

  def index
    @works = WorkSearch.new(query_params).search_results
    render json: @works.to_json
  end

  def show
    @work = WorkSearch.document(
      Work.find(params[:id])
    )
    render json: @work.to_json
  end

  def create
    work = WorkPosting.build(work_params).post!
    if work
      render json: { id: work.id }, status: :created
    else
      render json: { errors: work.errors }, status: :unprocessable_entity
    end
  end

  protected

  def query_params
    params.require(:query).permit(
      WorkSearch.permitted_params
    ).merge(current_user: current_user)
  end

  def work_params
    params.require(:work).permit(
      *Draft::FIELDS + [{
        chapters: [
          :content, :title, :notes, :endnotes, :summary, :position
        ]
      }]
    ).merge(user_id: current_user&.id)
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def new
  end

  def edit
  end

  def show
    @work = Work.find(params[:id]).decorate
  end

  def index
    @search = WorkSearch.new(search_params)
    @works = @search.search_results
  end

  def search_params
    basics = {
      filtered: true,
      page: params[:page] || 1,
      current_user: current_user
    }
    return basics if params[:query].blank?

    params.require(:query).permit(
      WorkSearch.permitted_params
    ).merge(basics)
  end
end

app/helpers/works_helper.rb
module WorksHelper
  # Given a particular set of facets/aggregations,
  # return the tag headings
  def tag_facet_keys
    Tag::TAGGABLE_TYPES.map { |tag_type| tag_type.underscore.pluralize }
  end

  # Don't collapse lists with selected filters
  def filter_group_div(search, facets, key)
    classes = 'filter collapse'
    values = facets[key]
    if values.blank? || search.send(values.first.field).present?
      classes += ' show'
    end
    content_tag(:div, class: classes, id: "collapse-#{key}") do
      yield
    end
  end
end

app/views/works/_blurb.html.erb
<div class="card">
  <div class="card-body blurb">
    <div class="header module">
      <h4 class="heading">
        <%= link_to work.title, work_path(id: work.id) %>
        by <%= work.creator_link_string %>
      </h4>

      <h5 class="fandoms heading">
        <span class="landmark">Fandoms</span>
        <%= work.fandom_link_string %>
      </h5>

      <%= work.icon_block %>
      <p class="datetime"><%= work.date_string %></p>
    </div>

    <h6 class="landmark heading">Tags</h6>
    <ul class="tags commas">
      <%= work.tag_li_list %>
    </ul>

    <!--summary-->
    <% unless work.summary.blank? %>
      <h6 class="landmark heading">Summary</h6>
      <blockquote class="userstuff summary">
        <%= work.summary.html_safe %>
      </blockquote>
    <% end %>

    <% unless work.series.empty? %>
      <h6 class="landmark heading">Series</h6>
      <ul class="series">
        <% work.series_html_links.each do |series_link| %>
          <li><%= series_link %></li>
        <% end %>
      </ul>
    <% end %>

    <dl class="stats basics">
      <dt class="language">Language:</dt>
      <dd class="language"><%= work.language %></dd>
      <dt class="words">Words:</dt>
      <dd class="words"><%= number_with_delimiter(work.word_count) %></dd>
      <dt class="chapters">Chapters:</dt>
      <dd class="chapters"><%= work.chapter_count %></dd>

      <% unless work.collections.empty? %>
        <dt class="collections">Collections:</dt>
        <dd class="collections"><%= work.collection_count_link %></dd>
      <% end %>
    </dl>
    <dl class="stats counts">
      <dt class="comments">Comments:</dt>
      <dd class="comments">
        <%= number_with_delimiter(work.comments_count) %>    
      </dd>
      <dt class="kudos">Kudos:</dt>
      <dd class="kudos">
        <%= number_with_delimiter(work.kudos_count) %>
      </dd>
      <dt class="bookmarks">Bookmarks:</dt>
      <dd class="bookmarks">
        <%= number_with_delimiter(work.bookmarks_count) %>
      </dd>
      <dt class="hits">Hits:</dt>
      <dd class="hits">
        <%= number_with_delimiter(work.hit_count) %>
      </dd>
    </dl>
  </div>
</div>

app/views/works/_chapter.html.erb
<div class="chapter">
  <%= chapter.content.html_safe %>
</div>

app/views/works/_filters.html.erb
<%= form_for @search, as: 'query', url: '/works', method: :get do |f| %>
  <p>
    <%= f.submit 'Filter Results', class: 'btn btn-outline-dark' %>  
  </p>

  <h4><%= f.label :sort_column, "Sort by" %></h4>
  <div class="sort">
    <%= f.select :sort_column, options_for_select(@search.sort_options, @search.sort_column) %>
  </div>

  <% tag_facet_keys.each do |key| %>
    <h4>
      <a data-toggle="collapse" href="#collapse-<%= key %>" aria-expanded="false" aria-controls="collapse-<%= key %>">
        <%= key.titleize %>
      </a>  
    </h4>
    <%= filter_group_div(@search, @works.facets, key) do %>
      <% @works.facets[key].each do |facet| %>
        <div class="facet">
          <%= f.check_box facet.field, { multiple: true }, facet.id.to_s, false %>
          <%= f.label facet.label_field, facet.label_name %>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <h4>
    Search Within Results
  </h4>
  <%= f.text_field :q %>

  <p style="margin-top: 1em">
    <%= f.submit 'Filter Results', class: 'btn btn-outline-dark' %>  
  </p>
<% end %>

app/views/works/_meta.html.erb
<div class="meta">
  <dl>
    <% Tag::TAGGABLE_TYPES.each do |tag_type| %>
      <%= work.tags_for_type(tag_type) %>
    <% end %>
    <dt>Language:</dt>
    <dd><%= work.language_name %></dd>
    <dt>Series:</dt>
    <dd>x</dd>
    <dt>Collections:</dt>
    <dd>x</dd>
    <dt>Stats:</dt>
    <dd>
      <dl>
        <dt>Published:</dt>
        <dd><%= work.revised_at %></dd>
        <dt>Words:</dt>
        <dd><%= number_with_delimiter(work.word_count) %></dd>
        <dt>Chapters:</dt>
        <dd><%= work.chapter_count %></dd>
      </dl>
      <dl>
        <dt>Comments:</dt>
        <dd><%= number_with_delimiter(work.comments_count) %></dd>
        <dt>Kudos:</dt>
        <dd><%= number_with_delimiter(work.kudos_count) %></dd>
        <dt>Bookmarks:</dt>
        <dd><%= number_with_delimiter(work.bookmarks_count) %></dd>
        <dt>Hits:</dt>
        <dd><%= number_with_delimiter(work.hit_count) %></dd>
      </dl>
    </dd>
  </dl>
  <div class="clear"></div>
</div>

app/views/works/edit.html.erb
<h1>Works#edit</h1>
<p>Find me in app/views/works/edit.html.erb</p>

app/views/works/index.html.erb
<h1>Works</h1>

<div id="works-index">
  <div class="works">
    <%= render partial: 'blurb', collection: @works, as: :work %>
  </div>
  <div class="filters">
    <div class="card">
      <div class="card-header">
        Filters
      </div>
      <div class="card-body">
        <%= render 'filters' %>
      </div>
    </div>
  </div>
</div>

<nav aria-label="Page navigation" class="pagination">
  <%= will_paginate @works %>
</nav>

app/views/works/new.html.erb
<h1>Works#new</h1>
<p>Find me in app/views/works/new.html.erb</p>

app/views/works/show.html.erb
<div id="work">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Navigate
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">View Full Work</a>
          <a class="dropdown-item" href="#">Jump to Comments</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Bookmark</a>
          <a class="dropdown-item" href="#">Mark For Later</a>
          <a class="dropdown-item" href="#">Subscribe</a>
          <a class="dropdown-item" href="#">Share</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Edit</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Download
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">HTML</a>
          <a class="dropdown-item" href="#">PDF</a>
          <a class="dropdown-item" href="#">MOBI</a>
          <a class="dropdown-item" href="#">EPUB</a>
        </div>
      </li>
    </ul>
  </nav>
  <%= render 'meta', work: @work %>

  <div class="preface">
    <h1 style="text-align: center"><%= @work.title %></h1>
    <h2 style="text-align: center">by <%= @work.creator_links %></h2>

    <% if @work.summary.present? %>
      <h3>Summary</h3>
      <div class="summary"><%= @work.summary.html_safe %></div>
    <% end %>

    <% if @work.notes.present? %>
      <h3>Notes</h3>
      <div class="notes"><%= @work.notes.html_safe %></div>
    <% end %>

  <%= render partial: 'chapter', collection: @work.chapters, as: :chapter %>

    <% if @work.endnotes.present? %>
      <h3>Notes</h3>
      <div class="notes"><%= @work.endnotes.html_safe %></div>
    <% end %>
</div>